name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '[]'
template: |
  ## What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/$REPOSITORY/compare/$PREVIOUS_TAG...$TAG
