name: 030-dotnet-workflow

on:
  push:
    branches: 
      - 'main'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-dotnet-app:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 03-app-dotnet

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
  
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Store build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          03-app-dotnet
          
    - name: Create release asset to attach
      shell: bash
      run: |
        tar -czvf build.tar.gz build
    - uses: release-drafter/release-drafter@v5.21.1
      env:
        GITHUB_TOKEN: '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'
        
          
      
